spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oliver-castillo/bank-config-repo
          clone-on-start: true
          force-pull: true
          default-label: main
server:
  port: 8888